[package]
name = "daiquiri"
version = "0.1.0"
authors = ["tmeumann <tom.meumann@ausport.gov.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["libpowerdna-sys"]

[dependencies]
libpowerdna-sys = { path = "libpowerdna-sys" }
ctrlc = "3.1"
enum_primitive = "0.1"
thiserror = "1.0"
tokio = { version = "0.2", features = ["full"] }
warp = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = "0.8"
rdkafka = { version = "0.24" }
