[package]
name = "daiquiri"
version = "0.1.0"
authors = ["tmeumann <tom.meumann@ausport.gov.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libpowerdna-sys = { git = "ssh://git@gitlab.com/ati-software-dev/powerdna-rust.git" }
ctrlc = "^3.1.6"
enum_primitive = "^0.1.1"
thiserror = "^1.0.20"
tokio = { version = "^0.2.22", features = ["full"] }
warp = "^0.2.5"
serde = { version = "^1.0.116", features = ["derive"] }
uuid = "0.8.1"
