FROM rust:latest

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get -y install build-essential ssh gdbserver \
    && apt-get clean

WORKDIR /pdna

COPY PowerDNA_Linux_4.10.1.14.tgz /pdna/
RUN tar xzf PowerDNA_Linux_4.10.1.14.tgz \
    && cd /pdna/PowerDNA_4.10.1/src \
    && make \
    && make install

RUN mkdir /etc/daiquiri && ln -s /app/streams.json /etc/daiquiri/streams.json

WORKDIR /app

COPY . /app

EXPOSE 3030 5555 1234

CMD ["bash"]
