FROM rust:1.56

WORKDIR /root

# dependencies for bindgen and flatbuffers
RUN apt update && \
    DEBIAN_FRONTEND=noninteractive apt -y install llvm-dev libclang-dev clang cmake

# build and install flatc, the flatbuffers compiler
RUN git clone --branch v2.0.0 --depth 1 https://github.com/google/flatbuffers.git && \
    cd flatbuffers && \
    cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release && \
    make && \
    make install

# build and install UEI's PowerDNA libraries
COPY PowerDNA_Linux_4.10.1.14.tgz .
RUN tar xzf PowerDNA_Linux_4.10.1.14.tgz && \
    cd PowerDNA_4.10.1/src && \
    make && \
    make install

# symlink daiquiri's config file to the shared volume
RUN mkdir /etc/daiquiri && ln -s /workspaces/daiquiri/streams.json /etc/daiquiri/streams.json

# build directory -- DO NOT MOUNT THIS TO THE HOST OS
VOLUME /target
ENV CARGO_TARGET_DIR=/target

# shared volume for the project directory
VOLUME /workspaces/daiquiri
WORKDIR /workspaces/daiquiri

EXPOSE 3030

CMD ["cargo", "run"]
