FROM ubuntu:20.04

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get -y install libzmq5 build-essential ssh gdbserver \
    && apt-get clean

RUN mkdir /app && mkdir /pdna && mkdir /etc/daiquiri
WORKDIR /pdna

COPY PowerDNA_Linux_4.10.1.14.tgz /pdna/
RUN tar xzf PowerDNA_Linux_4.10.1.14.tgz \
    && cd /pdna/PowerDNA_4.10.1/src \
    && make \
    && make install

WORKDIR /app

COPY streams.json /etc/daiquiri/streams.json
COPY . /app

EXPOSE 3030 5555 1234

ENTRYPOINT ["gdbserver", ":1234"]

CMD ["/app/target/x86_64-unknown-linux-gnu/debug/daiquiri"]
