[package]
name = "powerdna-sys"
version = "0.1.0"
authors = ["tmeumann <tom.meumann@ausport.gov.au>"]
edition = "2018"
links = "powerdna"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
bindgen="0.59"
