// automatically generated by the FlatBuffers compiler, do not modify



use std::mem;
use std::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::EndianScalar;

#[allow(unused_imports, dead_code)]
pub mod daiquiri {

  use std::mem;
  use std::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::EndianScalar;

pub enum SensorFrameOffset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct SensorFrame<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for SensorFrame<'a> {
    type Inner = SensorFrame<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table { buf: buf, loc: loc },
        }
    }
}

impl<'a> SensorFrame<'a> {
    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        SensorFrame {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args SensorFrameArgs<'args>) -> flatbuffers::WIPOffset<SensorFrame<'bldr>> {
      let mut builder = SensorFrameBuilder::new(_fbb);
      if let Some(x) = args.frame { builder.add_frame(x); }
      if let Some(x) = args.timestamps { builder.add_timestamps(x); }
      builder.add_samples(args.samples);
      builder.add_channels(args.channels);
      builder.finish()
    }

    pub const VT_CHANNELS: flatbuffers::VOffsetT = 4;
    pub const VT_SAMPLES: flatbuffers::VOffsetT = 6;
    pub const VT_TIMESTAMPS: flatbuffers::VOffsetT = 8;
    pub const VT_FRAME: flatbuffers::VOffsetT = 10;

  #[inline]
  pub fn channels(&self) -> u8 {
    self._tab.get::<u8>(SensorFrame::VT_CHANNELS, Some(0)).unwrap()
  }
  #[inline]
  pub fn samples(&self) -> u16 {
    self._tab.get::<u16>(SensorFrame::VT_SAMPLES, Some(0)).unwrap()
  }
  #[inline]
  pub fn timestamps(&self) -> Option<flatbuffers::Vector<'a, u32>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u32>>>(SensorFrame::VT_TIMESTAMPS, None)
  }
  #[inline]
  pub fn frame(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(SensorFrame::VT_FRAME, None)
  }
}

pub struct SensorFrameArgs<'a> {
    pub channels: u8,
    pub samples: u16,
    pub timestamps: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a ,  u32>>>,
    pub frame: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a ,  f64>>>,
}
impl<'a> Default for SensorFrameArgs<'a> {
    #[inline]
    fn default() -> Self {
        SensorFrameArgs {
            channels: 0,
            samples: 0,
            timestamps: None,
            frame: None,
        }
    }
}
pub struct SensorFrameBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> SensorFrameBuilder<'a, 'b> {
  #[inline]
  pub fn add_channels(&mut self, channels: u8) {
    self.fbb_.push_slot::<u8>(SensorFrame::VT_CHANNELS, channels, 0);
  }
  #[inline]
  pub fn add_samples(&mut self, samples: u16) {
    self.fbb_.push_slot::<u16>(SensorFrame::VT_SAMPLES, samples, 0);
  }
  #[inline]
  pub fn add_timestamps(&mut self, timestamps: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(SensorFrame::VT_TIMESTAMPS, timestamps);
  }
  #[inline]
  pub fn add_frame(&mut self, frame: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(SensorFrame::VT_FRAME, frame);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> SensorFrameBuilder<'a, 'b> {
    let start = _fbb.start_table();
    SensorFrameBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<SensorFrame<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

#[inline]
pub fn get_root_as_sensor_frame<'a>(buf: &'a [u8]) -> SensorFrame<'a> {
  flatbuffers::get_root::<SensorFrame<'a>>(buf)
}

#[inline]
pub fn get_size_prefixed_root_as_sensor_frame<'a>(buf: &'a [u8]) -> SensorFrame<'a> {
  flatbuffers::get_size_prefixed_root::<SensorFrame<'a>>(buf)
}

#[inline]
pub fn finish_sensor_frame_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<SensorFrame<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_sensor_frame_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<SensorFrame<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod Daiquiri

